# Semana 5: Introducción a Arreglos Multidimensionales con NumPy

### Importar la Librería NumPy

Para empezar a trabajar con NumPy, necesitamos importar la librería. NumPy es esencial para realizar cálculos matemáticos y manipular arreglos en Python.
Asegúrate de que tienes NumPy instalado antes de ejecutarlo.

In [2]:
import numpy as np

### Creación de Arreglos Unidimensionales
Vamos a crear un arreglo unidimensional sencillo y explorar sus propiedades.
Este tipo de arreglo se conoce como un vector y es la base para trabajar con arreglos más complejos.

**Pregunta a los estudiantes:**
- ¿Qué creen que representa cada índice en el arreglo?

In [8]:
mi_arreglo = np.array([1, 2, 3, 4, 5])
print("Mi arreglo unidimensional:", mi_arreglo)

arr_2=np.array([2,4,6])
print(arr_2)

type(arr_2)


Mi arreglo unidimensional: [1 2 3 4 5]
[2 4 6]


numpy.ndarray

In [7]:

type([2,4,6])

list

### Creación de Arreglos Multidimensionales

Ahora crearemos una matriz bidimensional, que tiene dos filas y tres columnas. Este tipo de arreglo es conocido como una matriz y se usa comúnmente para almacenar datos tabulares.


In [10]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz bidimensional:")
print(matriz)

type(matriz)

Matriz bidimensional:
[[1 2 3]
 [4 5 6]]


numpy.ndarray


**Ejercicio para los estudiantes:**
- Cree una matriz similar con sus propios valores.

In [14]:
matriz_p=np.array([[4,5,6],[10,20,30]])
print(matriz_p)

list_p=[[1,2],[3,4]]
print(f"No es una matris es una lista de listas {list_p}")

[[ 4  5  6]
 [10 20 30]]
No es una matris es una lista de listas [[1, 2], [3, 4]]


### Tipo de Datos en NumPy

Podemos definir el tipo de dato en nuestros arreglos. Por defecto, NumPy asigna el tipo según los elementos del arreglo, pero a veces es útil especificar el tipo manualmente para optimizar el uso de memoria o asegurar compatibilidad.

**Pregunta para los estudiantes:**
- ¿Por qué sería útil especificar el tipo de dato?

In [23]:
arreglo_flotante = np.array([1.5, 2.3, 3.1], dtype=np.float32)
print("Arreglo con tipo de dato flotante:", arreglo_flotante)

arreglo_flotante_1 = np.array([1.5, 2.3, 3.1], dtype=np.float16)
print("Arreglo con tipo de dato flotante 16 ", arreglo_flotante_1)

Arreglo con tipo de dato flotante: [1.5 2.3 3.1]
Arreglo con tipo de dato flotante 16  [1.5 2.3 3.1]


In [30]:
arreglo_flotante_2 = np.array([0, 2.3, 3.1], dtype=np.bool)
print(arreglo_flotante_2)

arreglo_flotante_3 = np.array([0, 2.3, 3.1], dtype=np.int32)
print(arreglo_flotante_3)

[False  True  True]
[0 2 3]


### Propiedades de un Arreglo

Vamos a explorar algunas propiedades útiles de los arreglos en NumPy:
- `shape`: Nos indica la forma del arreglo, es decir, el número de elementos en cada dimensión.
- `ndim`: Nos devuelve el número de dimensiones del arreglo.




In [36]:
mi_arreglo = np.array([1, 2, 3, 4, 5])

mamatriz_p=np.array([[4,5,6],[10,20,30]])

print("Forma del arreglo unidimensional:", mi_arreglo.shape)
print("Dimensiones de la matriz:", mi_arreglo.ndim)




Forma del arreglo unidimensional: (5,)
Dimensiones de la matriz: 1


**Ejercicio para los estudiantes:**
- Verifique las propiedades para la matriz que crearon.

In [35]:

print("Forma de la matriz ", mamatriz_p.shape)
print("Dimensiones de la matriz:", mamatriz_p.ndim)

Forma de la matriz  (2, 3)
Dimensiones de la matriz: 2


### Funciones para Crear Arreglos Rápidamente

NumPy proporciona funciones útiles para crear arreglos específicos de manera rápida:
- `np.zeros()`: Crea un arreglo lleno de ceros.
- `np.ones()`: Crea un arreglo lleno de unos.
- `np.arange()`: Genera un rango de números.

**Pregunta para los estudiantes:**
- ¿Para qué podría ser útil un arreglo de ceros?

In [53]:
ceros = np.zeros((3, 4))
print("Matriz de ceros (3x4):")
print(ceros)

print(ceros.ndim)

unos = np.ones((2, 5))
print("Matriz de unos (2x5):")
print(unos)

rango = np.arange(0, 10, 2)
print("Arreglo creado con np.arange:", rango)


lins=np.linspace(0,3,100)

print("Arreglo creado con np.linspace:", lins)

lins.shape

Matriz de ceros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
Matriz de unos (2x5):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Arreglo creado con np.arange: [0 2 4 6 8]
Arreglo creado con np.linspace: [0.         0.03030303 0.06060606 0.09090909 0.12121212 0.15151515
 0.18181818 0.21212121 0.24242424 0.27272727 0.3030303  0.33333333
 0.36363636 0.39393939 0.42424242 0.45454545 0.48484848 0.51515152
 0.54545455 0.57575758 0.60606061 0.63636364 0.66666667 0.6969697
 0.72727273 0.75757576 0.78787879 0.81818182 0.84848485 0.87878788
 0.90909091 0.93939394 0.96969697 1.         1.03030303 1.06060606
 1.09090909 1.12121212 1.15151515 1.18181818 1.21212121 1.24242424
 1.27272727 1.3030303  1.33333333 1.36363636 1.39393939 1.42424242
 1.45454545 1.48484848 1.51515152 1.54545455 1.57575758 1.60606061
 1.63636364 1.66666667 1.6969697  1.72727273 1.75757576 1.78787879
 1.81818182 1.84848485 1.87878788 1.90909091 1.93939394 1.96969697
 2.         2.03030303 2.06060606 2.09090909 2.12121212 2.15

(100,)

### Reshape de Arreglos

Podemos cambiar la forma de un arreglo siempre que el número de elementos sea el mismo usando `reshape()`.
Esto nos permite reorganizar los datos sin perder información.

**Ejercicio Práctico:**
- Tome un arreglo unidimensional y conviértalo en una matriz de forma 2x3.

In [55]:
arreglo_original = np.array([1, 2, 3, 4, 5, 6,7,8,9])
arreglo_reshaped = arreglo_original.reshape((3, 3,1))
print("Arreglo reshaped (2x3):")
print(arreglo_reshaped)

arreglo_reshaped.ndim

Arreglo reshaped (2x3):
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


3

### Operaciones Matemáticas sobre Arreglos

Las operaciones en NumPy se realizan sobre cada elemento del arreglo de manera vectorizada, lo cual es mucho más eficiente que usar bucles.

**Ejercicio para los estudiantes:**
- Realice una suma entre dos arreglos unidimensionales.

In [58]:
a = np.array([-1, -2, -3])
b = np.array([4, 5, 6])
suma = a - b
print("Suma de arreglos a y b:", suma)

Suma de arreglos a y b: [-5 -7 -9]


### Indexación y Slicing
La indexación y el slicing son técnicas fundamentales para seleccionar y trabajar con subconjuntos de datos dentro de un arreglo.

**Ejercicio para los estudiantes:**
- Cambiar los índices para acceder a diferentes elementos del arreglo.

In [70]:
arr_3=np.arange(0,20,5)
print(arr_3)


print("Primer elemento del arreglo:", arr_3[0])
print("Ultimo elemento del arreglo:", arr_3[-1]) #Todo: si se desconoce la longitud del vector
print("Sub-arreglo del original:", arr_3[0:3])  #Todo [n0,n-1] toma en cuenta los datos hasta el anterior numero que cierra el corchete

[ 0  5 10 15]
Primer elemento del arreglo: 0
Ultimo elemento del arreglo: 15
Sub-arreglo del original: [ 0  5 10]


### Ejercicio Final para los Estudiantes
- Cree un arreglo multidimensional que represente los datos de población de tres ciudades durante 5 años.
- Utilice `np.mean()` para calcular el promedio de la población de cada ciudad durante los 5 años.

In [74]:
ciudades= np.array([
    [340987, 673470, 563800, 345550, 877000],  #1
    [134670, 102000, 975236, 105000, 456740],  #2
    [235740, 202000, 324678, 672456, 345124]  #3
])

print(ciudades.shape)
# Calcular el promedio de la población 
promedio_ciudad1 = np.mean(ciudades[0])
promedio_ciudad2 = np.mean(ciudades[1])
promedio_ciudad3 = np.mean(ciudades[2])
# Agrupar los resultados en una lista
promedios = np.array([promedio_ciudad1, promedio_ciudad2, promedio_ciudad3], dtype=np.int32)
# Mostrar los resultados
print("Promedio de población de cada ciudad :", promedios)

(3, 5)
Promedio de población de cada ciudad : [560161 354729 355999]


In [77]:
# Crear un arreglo multidimensional para la población de tres ciudades durante 5 años
# Los datos son valores de ejemplo para ilustrar el código
poblacion = np.array([
    [100000, 105000, 110000, 115000, 120000],  # Ciudad Ambato
    [200000, 205000, 210000, 215000, 220000],  # Ciudad Cuenca
    [300000, 305000, 310000, 315000, 320000]   # Ciudad Quito
])

print(poblacion)
# Calcular el promedio de la población durante 5 años para cada ciudad
promedio_poblacion = np.mean(poblacion, axis=1)
print("Promedio de población en 5 años para cada ciudad:", promedio_poblacion)

[[100000 105000 110000 115000 120000]
 [200000 205000 210000 215000 220000]
 [300000 305000 310000 315000 320000]]
Promedio de población en 5 años para cada ciudad: [110000. 210000. 310000.]


### Reflexión para Hacer en Clase
- Utilicen NumPy para calcular la media y el valor máximo del arreglo creado.
- Reflexionen sobre qué significa cada cálculo y por qué sería importante en un contexto real (e.g., análisis de datos poblacionales).


Pueden ver cómo NumPy hace que las operaciones sean rápidas y eficientes, lo cual es clave en el análisis de grandes volúmenes de datos.