# Semana 5: Introducción a Arreglos Multidimensionales con NumPy

### Importar la Librería NumPy

Para empezar a trabajar con NumPy, necesitamos importar la librería. NumPy es esencial para realizar cálculos matemáticos y manipular arreglos en Python.
Asegúrate de que tienes NumPy instalado antes de ejecutarlo.

In [2]:
import numpy as np

### Creación de Arreglos Unidimensionales
Vamos a crear un arreglo unidimensional sencillo y explorar sus propiedades.
Este tipo de arreglo se conoce como un vector y es la base para trabajar con arreglos más complejos.

**Pregunta a los estudiantes:**
- ¿Qué creen que representa cada índice en el arreglo?

In [4]:
list_1=[1,2,3]
type(list_1)

list

In [5]:
mi_arreglo = np.array([1, 2, 3, 4, 5])
print("Mi arreglo unidimensional:", mi_arreglo)

type(mi_arreglo)

Mi arreglo unidimensional: [1 2 3 4 5]


numpy.ndarray

### Creación de Arreglos Multidimensionales

Ahora crearemos una matriz bidimensional, que tiene dos filas y tres columnas. Este tipo de arreglo es conocido como una matriz y se usa comúnmente para almacenar datos tabulares.


In [6]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz bidimensional:")
print(matriz)

Matriz bidimensional:
[[1 2 3]
 [4 5 6]]


In [8]:
m_1_l=[[1, 2, 3], [4, 5, 6]]
print(m_1_l)

[[1, 2, 3], [4, 5, 6]]



**Ejercicio para los estudiantes:**
- Cree una matriz similar con sus propios valores.

### Tipo de Datos en NumPy

Podemos definir el tipo de dato en nuestros arreglos. Por defecto, NumPy asigna el tipo según los elementos del arreglo, pero a veces es útil especificar el tipo manualmente para optimizar el uso de memoria o asegurar compatibilidad.

**Pregunta para los estudiantes:**
- ¿Por qué sería útil especificar el tipo de dato?

In [23]:
arreglo_flotante = np.array([1.5, 2.3, 3.1], dtype=np.float64)
print("Arreglo con tipo de dato flotante:", arreglo_flotante)


arreglo_flotante_bool = np.array([0, 2.3, 3.1], dtype=np.bool)
print(arreglo_flotante_bool)


arreglo_flotante_max = np.array([1.5, 6550400, 3.1], dtype=np.float32)
print("Arreglo con tipo de dato flotante:", arreglo_flotante_max)


Arreglo con tipo de dato flotante: [1.5 2.3 3.1]
[False  True  True]
Arreglo con tipo de dato flotante: [1.5000e+00 6.5504e+06 3.1000e+00]


### Propiedades de un Arreglo

Vamos a explorar algunas propiedades útiles de los arreglos en NumPy:
- `shape`: Nos indica la forma del arreglo, es decir, el número de elementos en cada dimensión.
- `ndim`: Nos devuelve el número de dimensiones del arreglo.




In [27]:
print("Forma del arreglo unidimensional:", mi_arreglo.shape)
print("Dimensiones de la matriz:", mi_arreglo.ndim)


tensor = np.array([[[1, 2, 3], [4, 5, 6]]])


print("Forma del tensor:", tensor.shape)
print("Dimensiones del tensor:", tensor.ndim)


Forma del arreglo unidimensional: (5,)
Dimensiones de la matriz: 1
Forma del tensor: (1, 2, 3)
Dimensiones del tensor: 3


**Ejercicio para los estudiantes:**
- Verifique las propiedades para la matriz que crearon.

### Funciones para Crear Arreglos Rápidamente

NumPy proporciona funciones útiles para crear arreglos específicos de manera rápida:
- `np.zeros()`: Crea un arreglo lleno de ceros.
- `np.ones()`: Crea un arreglo lleno de unos.
- `np.arange()`: Genera un rango de números.

**Pregunta para los estudiantes:**
- ¿Para qué podría ser útil un arreglo de ceros?

In [30]:
ceros = np.zeros((3, 4))
print("Matriz de ceros (3x4):")
print(ceros)

unos = np.ones((2, 5))
print("Matriz de unos (2x5):")
print(unos)

rango = np.arange(0, 10, 2)
print("Arreglo creado con np.arange:", rango)

lin=np.linspace(0,3,1000)
print("Arreglo creado con np.linspace:", lin)

Matriz de ceros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matriz de unos (2x5):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Arreglo creado con np.arange: [0 2 4 6 8]
Arreglo creado con np.linspace: [0.         0.003003   0.00600601 0.00900901 0.01201201 0.01501502
 0.01801802 0.02102102 0.02402402 0.02702703 0.03003003 0.03303303
 0.03603604 0.03903904 0.04204204 0.04504505 0.04804805 0.05105105
 0.05405405 0.05705706 0.06006006 0.06306306 0.06606607 0.06906907
 0.07207207 0.07507508 0.07807808 0.08108108 0.08408408 0.08708709
 0.09009009 0.09309309 0.0960961  0.0990991  0.1021021  0.10510511
 0.10810811 0.11111111 0.11411411 0.11711712 0.12012012 0.12312312
 0.12612613 0.12912913 0.13213213 0.13513514 0.13813814 0.14114114
 0.14414414 0.14714715 0.15015015 0.15315315 0.15615616 0.15915916
 0.16216216 0.16516517 0.16816817 0.17117117 0.17417417 0.17717718
 0.18018018 0.18318318 0.18618619 0.18918919 0.19219219 0.1951952
 0.1981982  0.2012012  0.2042042  0.20720721 0.21021021 0.2132

### Reshape de Arreglos

Podemos cambiar la forma de un arreglo siempre que el número de elementos sea el mismo usando `reshape()`.
Esto nos permite reorganizar los datos sin perder información.

**Ejercicio Práctico:**
- Tome un arreglo unidimensional y conviértalo en una matriz de forma 2x3.

In [36]:
arreglo_original = np.array([1, 2, 3, 4, 5, 6])
arreglo_reshaped = arreglo_original.reshape((2, 3))
print("Arreglo reshaped (2x3):")
print(arreglo_reshaped)

tensor_2 = arreglo_original.reshape((2, 3,1))
print(tensor_2)


arreglo_2= np.linspace(0,10,10)
arreglo_reshaped_2 = arreglo_2.reshape((5, 2))
print(arreglo_reshaped_2)

Arreglo reshaped (2x3):
[[1 2 3]
 [4 5 6]]
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[ 0.          1.11111111]
 [ 2.22222222  3.33333333]
 [ 4.44444444  5.55555556]
 [ 6.66666667  7.77777778]
 [ 8.88888889 10.        ]]


### Operaciones Matemáticas sobre Arreglos

Las operaciones en NumPy se realizan sobre cada elemento del arreglo de manera vectorizada, lo cual es mucho más eficiente que usar bucles.

**Ejercicio para los estudiantes:**
- Realice una suma entre dos arreglos unidimensionales.

In [43]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
suma = a + b
print("Suma de arreglos a y b:", suma)


sc=a*3
print(sc)

Suma de arreglos a y b: [5 7 9]
[3 6 9]


### Indexación y Slicing
La indexación y el slicing son técnicas fundamentales para seleccionar y trabajar con subconjuntos de datos dentro de un arreglo.

**Ejercicio para los estudiantes:**
- Cambiar los índices para acceder a diferentes elementos del arreglo.

In [54]:
print("Segundo elemento del arreglo:", mi_arreglo[1])
print("Sub-arreglo del original:", mi_arreglo[1:4])


v_1=np.linspace(0,30,5)
print(v_1)

print("Se imprimen la posicion 1,2,3",v_1[1:4]) #n-1 siendo n el ultimo valor del rango

Segundo elemento del arreglo: 2
Sub-arreglo del original: [2 3 4]
[ 0.   7.5 15.  22.5 30. ]
Se imprimen la posicion 1,2,3 [ 7.5 15.  22.5]


### Ejercicio Final para los Estudiantes
- Cree un arreglo multidimensional que represente los datos de población de tres ciudades durante 5 años.
- Utilice `np.mean()` para calcular el promedio de la población de cada ciudad durante los 5 años.

In [62]:
# Crear el arreglo multidimensional de población (3 ciudades, 5 años)
poblacion = np.array([[500000, 520000, 540000, 560000, 580000],  # Ciudad 1
                      [300000, 310000, 320000, 330000, 340000],  # Ciudad 2
                      [700000, 710000, 720000, 730000, 740000]]) # Ciudad 3

# Calcular el promedio de la población de cada ciudad durante los 5 años
promedio_ciudad = np.mean(poblacion,axis=1)

print(poblacion)

# Mostrar los resultados sin usar un bucle for
print("Promedio de población de cada ciudad durante 5 años:")
print(promedio_ciudad)

[[500000 520000 540000 560000 580000]
 [300000 310000 320000 330000 340000]
 [700000 710000 720000 730000 740000]]
Promedio de población de cada ciudad durante 5 años:
[540000. 320000. 720000.]


In [70]:


# Datos de población (en miles) para 3 ciudades durante 5 años
poblacion = np.array([
    [500, 520, 540, 560, 580],  # Ciudad 1
    [450, 460, 470, 480, 490],  # Ciudad 2
    [300, 320, 340, 360, 380]   # Ciudad 3
])

# Calcular el promedio de la población de cada ciudad a lo largo de los 5 años
promedio_poblacion = np.mean(poblacion, axis=1)

print("Promedio de población de cada ciudad durante 5 años:", promedio_poblacion)

Promedio de población de cada ciudad durante 5 años: [540. 470. 340.]


### Reflexión para Hacer en Clase
- Utilicen NumPy para calcular la media y el valor máximo del arreglo creado.
- Reflexionen sobre qué significa cada cálculo y por qué sería importante en un contexto real (e.g., análisis de datos poblacionales).


Pueden ver cómo NumPy hace que las operaciones sean rápidas y eficientes, lo cual es clave en el análisis de grandes volúmenes de datos.