### Introducción
En este notebook, realizaremos el preprocesamiento de datos utilizando NumPy. Aprenderemos cómo identificar y manejar valores faltantes, eliminar duplicados, detectar valores atípicos (outliers), y normalizar nuestros datos. El preprocesamiento es un paso crucial en la limpieza de datos antes de aplicar modelos de análisis o machine learning.

In [2]:
# Importar la librería NumPy
import numpy as np

### Crear Arreglo con Valores Faltantes
Primero, crearemos un arreglo que contiene algunos valores faltantes. Estos valores faltantes serán identificados y reemplazados en los siguientes pasos.

In [ ]:
datos = np.array([1, 2, np.nan, 4, 5, np.nan, 7])

print("Datos con valores faltantes (NaN):", datos)


Datos con valores faltantes (NaN): [ 1.  2. nan  4.  5. nan  7.]


### Identificar Valores Faltantes
Utilizamos la función `np.isnan()` para encontrar los valores faltantes (`NaN`). Esta función devuelve un arreglo booleano indicando qué elementos son `NaN`.


In [12]:
valores_faltantes = np.isnan(datos)
print("Valores nulos en el arreglo:", valores_faltantes)

Valores nulos en el arreglo: [False False  True False False  True False]


### Reemplazar Valores Faltantes
Una vez identificados los valores `NaN`, podemos reemplazarlos con la media de los valores no faltantes para mantener la coherencia del dataset.
```


In [14]:
media = np.nanmean(datos)  # Calcula la media sin considerar los NaN
datos_reemplazados = np.where(np.isnan(datos), media, datos)
print("Datos con NaN reemplazados por la media:", datos_reemplazados)

Datos con NaN reemplazados por la media: [1.  2.  3.8 4.  5.  3.8 7. ]


In [20]:
arr_1=[3 , np.nan, 6]
print(arr_1)

[3, nan, 6]


In [21]:

media_1 = np.nanmean(arr_1)

arr_fixed = np.where(np.isnan(arr_1),media_1 , arr_1)
 
print(arr_fixed)

arr_fixed_2 = np.where(np.isnan(arr_1),0 , arr_1)
print(arr_fixed_2)
 

[3.  4.5 6. ]
[3. 0. 6.]


### Eliminar Valores Duplicados
A continuación, creamos un nuevo arreglo con valores duplicados y utilizamos `np.unique()` para eliminar dichos duplicados.

In [22]:
datos_duplicados = np.array([1, 2, 2, 3, 4, 4, 5])
datos_unicos = np.unique(datos_duplicados)
print("Datos sin valores duplicados:", datos_unicos)

Datos sin valores duplicados: [1 2 3 4 5]


### Detectar Valores Atípicos (Outliers)
Para identificar valores que se encuentren fuera de un rango aceptable, calculamos la media y la desviación estándar del conjunto de datos y consideramos como outliers aquellos valores que estén a más de 2 desviaciones estándar de la media.

In [40]:
print(datos_reemplazados)

media = np.mean(datos_reemplazados)
desviacion = np.std(datos_reemplazados)
umbral = 2
outliers = datos_reemplazados[np.abs(datos_reemplazados - media) > umbral * desviacion]
print(outliers)
print("Valores atípicos (outliers):", outliers)


[1.  2.  3.8 4.  5.  3.8 7. ]
[]
Valores atípicos (outliers): []


### Normalizar Datos
Finalmente, normalizamos los datos para asegurarnos de que todos los valores se encuentren en un rango similar. Esto es útil para evitar que algunos valores con mayor magnitud dominen sobre otros durante el análisis.


In [42]:
datos_min = np.min(datos_reemplazados)
print(datos_min)
datos_max = np.max(datos_reemplazados)
print(datos_max)
datos_normalizados = (datos_reemplazados - datos_min) / (datos_max - datos_min)
print("Datos normalizados:", datos_normalizados)


1.0
7.0
Datos normalizados: [0.         0.16666667 0.46666667 0.5        0.66666667 0.46666667
 1.        ]


### Filtrar Valores Basados en una Condición
Podemos filtrar los valores que cumplan con una condición específica, como aquellos que sean mayores a un determinado umbral. En este ejemplo, seleccionamos los valores mayores a 4.


In [44]:

valores_mayores = datos_reemplazados[datos_reemplazados > 1]
print("Valores mayores a 4:", valores_mayores)


Valores mayores a 4: [2.  3.8 4.  5.  3.8 7. ]


### Conclusión
El preprocesamiento de datos con NumPy incluye una serie de técnicas fundamentales que ayudan a mejorar la calidad de los datos para análisis posteriores. Estas incluyen la identificación y manejo de valores faltantes, la eliminación de duplicados, la detección de outliers y la normalización de datos. NumPy nos proporciona herramientas eficientes y rápidas para llevar a cabo estos procesos.

### Leer un archivo CSV
Podemos usar la función `np.genfromtxt()` para leer datos de un archivo CSV. Esta función es especialmente útil cuando los datos contienen valores faltantes.

In [3]:
# Asegúrate de tener un archivo CSV llamado 'datos.csv' en el mismo directorio
datos_csv = np.genfromtxt('student-mat.csv', delimiter=',', skip_header=1)
print("Datos leídos del archivo CSV:")
print(datos_csv)

Datos leídos del archivo CSV:
[[nan nan 18. ...  5.  6.  6.]
 [nan nan 17. ...  5.  5.  6.]
 [nan nan 15. ...  7.  8. 10.]
 ...
 [nan nan 21. ... 10.  8.  7.]
 [nan nan 18. ... 11. 12. 10.]
 [nan nan 19. ...  8.  9.  9.]]


In [4]:
datos_csv = np.where(np.isnan(datos_csv), 0, datos_csv)
print(datos_csv)

[[ 0.  0. 18. ...  5.  6.  6.]
 [ 0.  0. 17. ...  5.  5.  6.]
 [ 0.  0. 15. ...  7.  8. 10.]
 ...
 [ 0.  0. 21. ... 10.  8.  7.]
 [ 0.  0. 18. ... 11. 12. 10.]
 [ 0.  0. 19. ...  8.  9.  9.]]


In [5]:
np.shape(datos_csv)

(395, 33)

In [6]:
walc=datos_csv[:,-10:-6]
print(walc)


dalc=datos_csv[:,-7]

print(dalc)

[[4. 3. 4. 1.]
 [5. 3. 3. 1.]
 [4. 3. 2. 2.]
 ...
 [5. 5. 3. 3.]
 [4. 4. 1. 3.]
 [3. 2. 3. 3.]]
[1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2.
 1. 1. 1. 2. 1. 5. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1.
 2. 1. 2. 1. 3. 2. 4. 1. 1. 1. 1. 1. 2. 5. 1. 2. 2. 1. 5. 1. 1. 2. 1. 1.
 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 3. 1. 1. 2. 1. 1. 1.
 1. 1. 1. 1. 5. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 3.
 1. 1. 1. 1. 2. 2. 2. 3. 2. 1. 1. 1. 3. 1. 1. 4. 2. 1. 2. 1. 1. 1. 2. 1.
 1. 1. 2. 1. 1. 1. 1. 4. 1. 1. 3. 1. 2. 1. 2. 2. 1. 2. 1. 1. 1. 1. 1. 1.
 4. 3. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 1. 3. 2. 1. 1. 1. 1. 4. 1. 2. 1. 1.
 2. 2. 1. 1. 1. 1. 1. 5. 1. 1. 1. 1. 4. 1. 1. 1. 1. 2. 1. 1. 5. 1. 1. 3.
 1. 2. 1. 1. 1. 1. 1. 5. 1. 2. 2. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 3. 3. 2. 1. 1. 3. 1. 1. 2. 1. 2. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 2. 

In [72]:
mean_walc=np.mean(walc)
mean_dalc=np.mean(dalc)


print(f"Promedio de consumo de alcohol en fines de semana {mean_walc}")

print(f"Promedio de consumo de alcohol en dias entresemana {mean_dalc}")


print(np.std(walc))
print(np.std(dalc))

Promedio de consumo de alcohol en fines de semana 2.2911392405063293
Promedio de consumo de alcohol en dias entresemana 1.481012658227848
1.2862653104886688
0.8896131927704095
