# Notebook: Métodos Avanzados de NumPy

In [3]:
import numpy as np

### Inversa de una Matriz
En este ejemplo, calculamos la inversa de la matriz A.

In [4]:
A = np.array([[1, 2], [3, 4]])
print(A)
inversa_A = np.linalg.inv(A)
print("Inversa de A:")
print(inversa_A)

[[1 2]
 [3 4]]
Inversa de A:
[[-2.   1. ]
 [ 1.5 -0.5]]


### Determinante de una Matriz
Calculamos el determinante de la matriz A.

In [16]:
det_A = np.linalg.det(A)
ReferenceError
print(f"Determinante de A: {det_A:.0f} ")

Determinante de A: -2 


### Valores y Vectores Propios de una Matriz
Calculamos los valores y vectores propios de la matriz A.

In [24]:
B=np.arange(5,50,5)
print(B)
B=B.reshape(3,3)

[ 5 10 15 20 25 30 35 40 45]


In [17]:
eig_values, eig_vectors = np.linalg.eig(A)
print("Valores propios de A:", eig_values)
print("Vectores propios de A:")
print(eig_vectors)

Valores propios de A: [-0.37228132  5.37228132]
Vectores propios de A:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [27]:
eig_values_B, eig_vectors_B = np.linalg.eig(B)
print("Valores propios de B:", eig_values_B)
print("Vectores propios de B:")
print(eig_vectors_B)

Valores propios de B: [ 8.05842198e+01 -5.58421985e+00  4.15330564e-16]
Vectores propios de B:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


 ### Resolución de un Sistema de Ecuaciones Lineales
 Resolvemos el sistema Ax = b, donde A es una matriz 3x3 y b es un vector.

 El sistema de ecuaciones tiene la forma:

$$
A \cdot \mathbf{x} = \mathbf{b}
$$

Donde:

$$
A =
\begin{bmatrix}
3 & 1 & 2 \\
1 & 2 & 3 \\
2 & 3 & 1
\end{bmatrix}, \quad
\mathbf{b} =
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}
$$

Esto corresponde al sistema:

$$
\begin{aligned}
3x_1 + x_2 + 2x_3 &= 1 \\
x_1 + 2x_2 + 3x_3 &= 2 \\
2x_1 + 3x_2 + x_3 &= 3
\end{aligned}
$$

 

In [38]:
A = np.array([[5, 1, 2], [1, 6, 3], [2, 3, 1]])
b = np.array([1, 2, 3])
x = np.linalg.solve(A, b)
print("Solución del sistema de ecuaciones:", x) 

Solución del sistema de ecuaciones: [ 0.71428571  1.14285714 -1.85714286]


In [37]:
A_inv=np.linalg.inv(A)
X=np.dot(A_inv,b)
print(X)

[ 0.71428571  1.14285714 -1.85714286]


## Transformadas de Fourier con NumPy

### Transformada de Fourier de una Señal
Calculamos la transformada de Fourier de una señal de ejemplo.

In [39]:
signal = np.array([1, 2, 3, 4])
fft_signal = np.fft.fft(signal)
print("Transformada de Fourier de la señal:", fft_signal)

Transformada de Fourier de la señal: [10.+0.j -2.+2.j -2.+0.j -2.-2.j]


### Transformada Inversa de Fourier
Calculamos la transformada inversa de Fourier para volver al dominio del tiempo.

In [40]:
ifft_signal = np.fft.ifft(fft_signal)
print("Transformada inversa de Fourier:", ifft_signal)

Transformada inversa de Fourier: [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


## Estadísticas y Probabilidades con NumPy

### Percentil de un Conjunto de Datos
Calculamos el percentil 50 (mediana) de un conjunto de datos.

In [48]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
percentile_50 = np.percentile(data, 50)
print("Percentil 50 (mediana):", percentile_50)

percentile_25 = np.quantile(data, 0.25)
print("Percentil 25 :", percentile_25)

Percentil 50 (mediana): 5.0
Percentil 25 : 3.0


### Covarianza entre Variables
Calculamos la matriz de covarianza entre variables.

In [51]:
cov_matrix = np.cov(data)
print("Matriz de covarianza:")
print(cov_matrix)

Matriz de covarianza:
7.5


 ### Coeficiente de Correlación entre Variables
Calculamos la correlación entre dos conjuntos de datos.

In [58]:
data1 = np.array([67, 23, 50, 56, 103])
data2 = np.array([30, 20.4, 40.3, 0.2, 0.1])
correlation = np.corrcoef(data1, data2)
print("Coeficiente de correlación entre data1 y data2:")
print(correlation)

Coeficiente de correlación entre data1 y data2:
[[ 1.       -0.444345]
 [-0.444345  1.      ]]


## Cálculos Matemáticos Avanzados

 ### Gradiente de un Array
 Calculamos el gradiente de un conjunto de datos para obtener la pendiente.

In [59]:
gradient = np.gradient(data)
print("Gradiente del array:", gradient)

Gradiente del array: [1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [60]:
gradient_2= np.gradient(data2)
print("Gradiente del array:", gradient_2)

Gradiente del array: [ -9.6    5.15 -10.1  -20.1   -0.1 ]


### Diferencias entre Elementos Consecutivos
Calculamos las diferencias entre elementos consecutivos en el array.

In [61]:
differences = np.diff(data)
print("Diferencias entre elementos consecutivos:", differences)

Diferencias entre elementos consecutivos: [1 1 1 1 1 1 1 1]


In [62]:
differences_2 = np.diff(data2)
print("Diferencias entre elementos consecutivos:", differences_2)

Diferencias entre elementos consecutivos: [ -9.6  19.9 -40.1  -0.1]


 ### Integración Numérica con la Regla del Trapecio
Calculamos el área bajo la curva usando la regla del trapecio.

In [76]:
y = np.array([1, 3, 7, 10])
x = np.array([0, 1, 2, 3])
area = np.trapezoid(y, x,dx=2,axis=0)
print("Área bajo la curva:", area)

Área bajo la curva: 15.5


 ## Ejercicio Práctico para Estudiantes
 Comentario: Ejercicio práctico para que los estudiantes resuelvan en clase.
Enunciado: Utilizando NumPy, realice los siguientes pasos:
1. Cree una matriz A de tamaño 4x4 con valores aleatorios enteros entre 1 y 10.
2. Calcule la inversa de la matriz A.
3. Cree un vector b de tamaño 4 con valores aleatorios enteros entre 1 y 10.
4. Resuelva el sistema de ecuaciones Ax = b. De manera matricial 
5. Realice la descomposición en Valores y Vectores Propios de la matriz A.