# Notebook: Métodos Avanzados de NumPy

In [1]:
import numpy as np

### Inversa de una Matriz
En este ejemplo, calculamos la inversa de la matriz A.

In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A)
inversa_A = np.linalg.inv(A)
print("Inversa de A:")
print(inversa_A)

[[1 2]
 [3 4]]
Inversa de A:
[[-2.   1. ]
 [ 1.5 -0.5]]


### Determinante de una Matriz
Calculamos el determinante de la matriz A.

In [7]:
det_A = np.linalg.det(A)
print(f"Determinante de A: {det_A:.0f}")

Determinante de A: -2


### Valores y Vectores Propios de una Matriz
Calculamos los valores y vectores propios de la matriz A.

In [ ]:
eig_values, eig_vectors = np.linalg.eig(A)
print("Valores propios de A:", eig_values)
print("Vectores propios de A:")
print(eig_vectors)

Valores propios de A: [-0.37228132  5.37228132]
Vectores propios de A:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [14]:
B=np.arange(1,10,1)
print(B)
B=B.reshape(3,3)
print(B)

eig_values_b, eig_vectors_b = np.linalg.eig(B)
print("Valores propios de A:", eig_values_b)
print("Vectores propios de A:")
print(eig_vectors_b)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Valores propios de A: [ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
Vectores propios de A:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


 ### Resolución de un Sistema de Ecuaciones Lineales
 Resolvemos el sistema Ax = b, donde A es una matriz 3x3 y b es un vector.

 El sistema de ecuaciones tiene la forma:

$$
A \cdot \mathbf{x} = \mathbf{b}
$$

Donde:

$$
A =
\begin{bmatrix}
3 & 1 & 2 \\
1 & 2 & 3 \\
2 & 3 & 1
\end{bmatrix}, \quad
\mathbf{b} =
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}
$$

Esto corresponde al sistema:

$$
\begin{aligned}
3x_1 + x_2 + 2x_3 &= 1 \\
x_1 + 2x_2 + 3x_3 &= 2 \\
2x_1 + 3x_2 + x_3 &= 3
\end{aligned}
$$

 

In [15]:
A = np.array([[3, 1, 2], [1, 2, 3], [2, 3, 1]])
b = np.array([1, 2, 3])
x = np.linalg.solve(A, b)
print("Solución del sistema de ecuaciones:", x)

Solución del sistema de ecuaciones: [ 0.00000000e+00  1.00000000e+00 -2.67275913e-17]


In [16]:
A = np.array([[5, 1, 2], [1, 6, 3], [2, 3, 1]])
b = np.array([1, 2, 3])

In [20]:
A_inv=np.linalg.inv(A)

X=np.dot(A_inv,b)
print(X)

[ 0.71428571  1.14285714 -1.85714286]


In [22]:
X=np.linalg.solve(A,b)
print(X)

[ 0.71428571  1.14285714 -1.85714286]


## Transformadas de Fourier con NumPy

### Transformada de Fourier de una Señal
Calculamos la transformada de Fourier de una señal de ejemplo.

In [23]:
signal = np.array([1, 2, 3, 4])
fft_signal = np.fft.fft(signal)
print("Transformada de Fourier de la señal:", fft_signal)

Transformada de Fourier de la señal: [10.+0.j -2.+2.j -2.+0.j -2.-2.j]


### Transformada Inversa de Fourier
Calculamos la transformada inversa de Fourier para volver al dominio del tiempo.

In [24]:
ifft_signal = np.fft.ifft(fft_signal)
print("Transformada inversa de Fourier:", ifft_signal)

Transformada inversa de Fourier: [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


## Estadísticas y Probabilidades con NumPy

### Percentil de un Conjunto de Datos
Calculamos el percentil 50 (mediana) de un conjunto de datos.

In [29]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8])
percentile_50 = np.percentile(data, 50)
print("Percentil 50 (mediana):", percentile_50)

Percentil 50 (mediana): 4.5


In [31]:
quantile_50 = np.quantile(data, 0.5)
print(quantile_50)

4.5


### Covarianza entre Variables
Calculamos la matriz de covarianza entre variables.

In [32]:
cov_matrix = np.cov(data)
print("Matriz de covarianza:")
print(cov_matrix)

Matriz de covarianza:
6.0


In [34]:
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([5, 4, 3, 2, 1])

cov_matrix = np.cov(data1,data2)
print(cov_matrix)

[[ 2.5 -2.5]
 [-2.5  2.5]]


 ### Coeficiente de Correlación entre Variables
Calculamos la correlación entre dos conjuntos de datos.

In [35]:
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([5, 4, 3, 2, 1])
correlation = np.corrcoef(data1, data2)
print("Coeficiente de correlación entre data1 y data2:")
print(correlation)

Coeficiente de correlación entre data1 y data2:
[[ 1. -1.]
 [-1.  1.]]


In [36]:
data1 = np.array([1, 2000, 0.33, 45, 3455])
data2 = np.array([5, 4, 3, 2, 1])

In [37]:
correlation = np.corrcoef(data1, data2)
print("Coeficiente de correlación entre data1 y data2:")
print(correlation)

Coeficiente de correlación entre data1 y data2:
[[ 1.         -0.49814444]
 [-0.49814444  1.        ]]


## Cálculos Matemáticos Avanzados

 ### Gradiente de un Array
 Calculamos el gradiente de un conjunto de datos para obtener la pendiente.

In [40]:
print(data1)
gradient = np.gradient(data1)
print("Gradiente del array:", gradient)

[1.000e+00 2.000e+03 3.300e-01 4.500e+01 3.455e+03]
Gradiente del array: [ 1.999000e+03 -3.350000e-01 -9.775000e+02  1.727335e+03  3.410000e+03]


### Diferencias entre Elementos Consecutivos
Calculamos las diferencias entre elementos consecutivos en el array.

In [41]:
differences = np.diff(data1)
print("Diferencias entre elementos consecutivos:", differences)

Diferencias entre elementos consecutivos: [ 1999.   -1999.67    44.67  3410.  ]


 ### Integración Numérica con la Regla del Trapecio
Calculamos el área bajo la curva usando la regla del trapecio.

In [ ]:
y = np.array([1, 3, 7, 10])
x = np.array([0, 1, 2, 3])
area = np.trapezoid(y, x)
print("Área bajo la curva:", area)

Área bajo la curva: 15.5


In [47]:
def square (x): #Todo: Funcion 
    return x ** 2
vectorized_square = np. vectorize ( square )
data = np. array ([1 , 2, 3, 4])
result = vectorized_square ( data )
print ( result )



def cubic (x): #Todo: Funcion 
    return x ** 3

vectorized_cubic = np. vectorize ( cubic )
data = np. array ([1 , 2, 3, 4])
result = vectorized_cubic ( data )
print ( result )

[ 1  4  9 16]
[ 1  8 27 64]


In [ ]:
x = np. array ([0 , 1, 2])
y = np. array ([0 , 10, 20])

x_new = np. array ([0.5 , 1.5])

y_new = np.interp (x_new , x, y)

print ( y_new )

[ 5. 15.]


In [49]:
normal_data = np. random . randn (3, 3)
print ( normal_data )

[[ 0.75164068  1.31217283 -1.71323641]
 [ 0.44682484  1.81563289 -1.26169734]
 [ 0.14543517 -0.81452613  1.50989248]]


In [52]:
x = np. linspace (-1, 1, 5)

print(x)

y = np. linspace (-1, 1, 5)
print(y)
X, Y = np. meshgrid (x, y)
print ("X:", X)
print ("Y:", Y)


[-1.  -0.5  0.   0.5  1. ]
[-1.  -0.5  0.   0.5  1. ]
X: [[-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]]
Y: [[-1.  -1.  -1.  -1.  -1. ]
 [-0.5 -0.5 -0.5 -0.5 -0.5]
 [ 0.   0.   0.   0.   0. ]
 [ 0.5  0.5  0.5  0.5  0.5]
 [ 1.   1.   1.   1.   1. ]]


In [53]:
v1 = np. array ([1 , 2])
v2 = np. array ([3 , 4])
outer_product = np. outer (v1 , v2)
print ( outer_product )

[[3 4]
 [6 8]]


 ## Ejercicio Práctico para Estudiantes
 Comentario: Ejercicio práctico para que los estudiantes resuelvan en clase.
Enunciado: Utilizando NumPy, realice los siguientes pasos:
1. Cree una matriz A de tamaño 4x4 con valores aleatorios enteros entre 1 y 10.
2. Calcule la inversa de la matriz A.
3. Cree un vector b de tamaño 4 con valores aleatorios enteros entre 1 y 10.
4. Resuelva el sistema de ecuaciones Ax = b.
5. Realice la descomposición en valores singulares (SVD) de la matriz A. y explicar que hace, puntos extra