In [1]:
import numpy  as np 


In [3]:

A=np.arange(0,10,3)
B=np.arange(0,10,2)

print(A)
print(B)

[0 3 6 9]
[0 2 4 6 8]


In [8]:
C=np.hstack((A,B))
print(C)


[0 3 6 9 0 2 4 6 8]


In [10]:
Co=np.concatenate((A,B))
print(Co)

[0 3 6 9 0 2 4 6 8]


In [20]:
A_1=np.append(A,[10])
print(A_1)
print(B)
type(B)

[ 0  3  6  9 10]
[0 2 4 6 8]


numpy.ndarray

In [26]:
F=np.vstack((A_1,B))
print(F)
np.shape(F)


[[ 0  3  6  9 10]
 [ 0  2  4  6  8]]


(2, 5)

In [39]:
np.split(F,1,axis=0)

[array([[ 0,  3,  6,  9, 10],
        [ 0,  2,  4,  6,  8]])]

In [41]:
F_1=F[0,:]
print(F_1)

[ 0  3  6  9 10]


In [50]:
F_1=np.append(F_1,12)
print(F_1)

[ 0  3  6  9 10 12]


In [60]:
Div=np.split(F_1,3)
print(Div)

Div_0=Div[0]
print(Div_0[1])

[array([0, 3]), array([6, 9]), array([10, 12])]
3
